apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      name: postgres
      labels:
        component: postgres
    spec:
      volumes:
        - name: pvc-v2
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass
                  key: pg-pass
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pvc-v2
              mountPath: /var/lib/postgresql/data
              subPath: postgres